Add view-role page
is212-team7/is212-g5t7 pull request #9
Opened 2022-10-13 03:26 UTC by bayberryy

2022-10-17 08:00 UTC, gilite requested changes

2022-10-17 08:00 UTC, regexyl commented on client/pages/view-role.tsx
> +                        ))}
Could you refactor this static content into a dynamic one? [Here's an example](https://github.com/is212-team7/is212-g5t7/pull/7/commits/c0a5452ef85b37523061d80ed92fa69fbb20c6cb) :D

We could squash it down to ~50 lines with that.

2022-10-17 08:00 UTC, gilite commented on client/pages/database/roles.ts
> +export const roles = {
Could you pull from the `master` branch and then move this `client/pages/database/roles.ts` to `client/database/roles.ts`?

I think we will have a build error if we put our in-memory database under the `pages` folder.

2022-10-18 00:16 UTC, bayberryy commented on client/pages/view-role.tsx
> +                        ))}
Changed it!

2022-10-18 00:27 UTC, gilite approved these changes

2022-10-18 00:30 UTC, merged